// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card_event_logs.sql

package db

import (
	"context"
)

const insertCardEventLog = `-- name: InsertCardEventLog :one
INSERT INTO card_event_logs (
    topic,
    event_type,
    card_number,
    reference_id,
    payload
)
VALUES ($1, $2, NULLIF($3::text, ''), NULLIF($4::text, ''), $5::jsonb)
ON CONFLICT DO NOTHING
RETURNING event_id, topic, event_type, card_number, reference_id, payload, received_at
`

type InsertCardEventLogParams struct {
	Topic       string `json:"topic"`
	EventType   string `json:"event_type"`
	CardNumber  string `json:"card_number"`
	ReferenceID string `json:"reference_id"`
	Payload     []byte `json:"payload"`
}

func (q *Queries) InsertCardEventLog(ctx context.Context, arg InsertCardEventLogParams) (*CardEventLog, error) {
	row := q.db.QueryRow(ctx, insertCardEventLog,
		arg.Topic,
		arg.EventType,
		arg.CardNumber,
		arg.ReferenceID,
		arg.Payload,
	)
	var i CardEventLog
	err := row.Scan(
		&i.EventID,
		&i.Topic,
		&i.EventType,
		&i.CardNumber,
		&i.ReferenceID,
		&i.Payload,
		&i.ReceivedAt,
	)
	return &i, err
}
