// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant_document.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchantDocument = `-- name: CreateMerchantDocument :one
WITH valid_merchant AS (
    SELECT m.merchant_id, u.email
    FROM merchants m
    JOIN users u ON u.user_id = m.user_id AND u.deleted_at IS NULL
    WHERE m.merchant_id = $1 AND m.deleted_at IS NULL
), inserted_document AS (
    INSERT INTO merchant_documents (
        merchant_id, document_type, document_url, status, note, uploaded_at, updated_at
    )
    SELECT merchant_id, $2, $3, $4, $5, current_timestamp, current_timestamp
    FROM valid_merchant
    RETURNING document_id, merchant_id, document_type, document_url, status, note, uploaded_at, created_at, updated_at
), queued_event AS (
    INSERT INTO outbox_events (event_key, topic, message_key, payload)
    SELECT
        'merchant-document-create:' || document_id::text,
        'email-service-topic-merchant-document-create',
        document_id::text,
        jsonb_build_object(
            'event_id', gen_random_uuid()::text,
            'schema_version', 1,
            'event_type', 'merchant_document.created',
            'occurred_at', now(),
            'email', u.email,
            'subject', 'Merchant Verification Pending - Action Required',
            'body', 'Your merchant document has been submitted and is pending review.'
        )
    FROM inserted_document d
    JOIN valid_merchant u ON u.merchant_id = d.merchant_id
    ON CONFLICT (event_key) DO NOTHING
    RETURNING event_key
)
SELECT document_id, merchant_id, document_type, document_url, status, note, uploaded_at, created_at, updated_at
FROM inserted_document
`

type CreateMerchantDocumentParams struct {
	MerchantID   int32   `json:"merchant_id"`
	DocumentType string  `json:"document_type"`
	DocumentUrl  string  `json:"document_url"`
	Status       string  `json:"status"`
	Note         *string `json:"note"`
}

type CreateMerchantDocumentRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateMerchantDocument(ctx context.Context, arg CreateMerchantDocumentParams) (*CreateMerchantDocumentRow, error) {
	row := q.db.QueryRow(ctx, createMerchantDocument,
		arg.MerchantID,
		arg.DocumentType,
		arg.DocumentUrl,
		arg.Status,
		arg.Note,
	)
	var i CreateMerchantDocumentRow
	err := row.Scan(
		&i.DocumentID,
		&i.MerchantID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Status,
		&i.Note,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAllPermanentMerchantDocuments = `-- name: DeleteAllPermanentMerchantDocuments :exec
DELETE FROM merchant_documents WHERE deleted_at IS NOT NULL
`

func (q *Queries) DeleteAllPermanentMerchantDocuments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPermanentMerchantDocuments)
	return err
}

const deleteMerchantDocumentPermanently = `-- name: DeleteMerchantDocumentPermanently :exec
DELETE FROM merchant_documents
WHERE
    document_id = $1
    AND deleted_at IS NOT NULL
`

func (q *Queries) DeleteMerchantDocumentPermanently(ctx context.Context, documentID int32) error {
	_, err := q.db.Exec(ctx, deleteMerchantDocumentPermanently, documentID)
	return err
}

const getActiveMerchantDocuments = `-- name: GetActiveMerchantDocuments :many
SELECT
    document_id,
    merchant_id,
    document_type,
    document_url,
    status,
    note,
    uploaded_at,
    created_at,
    updated_at,
    deleted_at,
    COUNT(*) OVER () AS total_count
FROM merchant_documents
WHERE
    deleted_at IS NULL
    AND status != 'deleted'
    AND (
        $1::TEXT IS NULL
        OR document_type ILIKE '%' || $1 || '%'
        OR status ILIKE '%' || $1 || '%'
        OR note ILIKE '%' || $1 || '%'
    )
ORDER BY document_id
LIMIT $2
OFFSET
    $3
`

type GetActiveMerchantDocumentsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetActiveMerchantDocumentsRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	TotalCount   int64            `json:"total_count"`
}

func (q *Queries) GetActiveMerchantDocuments(ctx context.Context, arg GetActiveMerchantDocumentsParams) ([]*GetActiveMerchantDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getActiveMerchantDocuments, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetActiveMerchantDocumentsRow
	for rows.Next() {
		var i GetActiveMerchantDocumentsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.MerchantID,
			&i.DocumentType,
			&i.DocumentUrl,
			&i.Status,
			&i.Note,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantDocument = `-- name: GetMerchantDocument :one
SELECT
    document_id,
    merchant_id,
    document_type,
    document_url,
    status,
    note,
    uploaded_at,
    created_at,
    updated_at
FROM merchant_documents
WHERE
    document_id = $1
    AND deleted_at IS NULL
`

type GetMerchantDocumentRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetMerchantDocument(ctx context.Context, documentID int32) (*GetMerchantDocumentRow, error) {
	row := q.db.QueryRow(ctx, getMerchantDocument, documentID)
	var i GetMerchantDocumentRow
	err := row.Scan(
		&i.DocumentID,
		&i.MerchantID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Status,
		&i.Note,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantDocuments = `-- name: GetMerchantDocuments :many
SELECT
    document_id,
    merchant_id,
    document_type,
    document_url,
    status,
    note,
    uploaded_at,
    created_at,
    updated_at,
    COUNT(*) OVER () AS total_count
FROM merchant_documents
WHERE
    deleted_at IS NULL
    AND (
        $1::TEXT IS NULL
        OR document_type ILIKE '%' || $1 || '%'
        OR status ILIKE '%' || $1 || '%'
        OR note ILIKE '%' || $1 || '%'
    )
ORDER BY document_id
LIMIT $2
OFFSET
    $3
`

type GetMerchantDocumentsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetMerchantDocumentsRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TotalCount   int64            `json:"total_count"`
}

func (q *Queries) GetMerchantDocuments(ctx context.Context, arg GetMerchantDocumentsParams) ([]*GetMerchantDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getMerchantDocuments, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetMerchantDocumentsRow
	for rows.Next() {
		var i GetMerchantDocumentsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.MerchantID,
			&i.DocumentType,
			&i.DocumentUrl,
			&i.Status,
			&i.Note,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrashedMerchantDocuments = `-- name: GetTrashedMerchantDocuments :many
SELECT
    document_id,
    merchant_id,
    document_type,
    document_url,
    status,
    note,
    uploaded_at,
    created_at,
    updated_at,
    deleted_at,
    COUNT(*) OVER () AS total_count
FROM merchant_documents
WHERE
    deleted_at IS NOT NULL
    AND (
        $1::TEXT IS NULL
        OR document_type ILIKE '%' || $1 || '%'
        OR status ILIKE '%' || $1 || '%'
        OR note ILIKE '%' || $1 || '%'
    )
ORDER BY document_id
LIMIT $2
OFFSET
    $3
`

type GetTrashedMerchantDocumentsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTrashedMerchantDocumentsRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	TotalCount   int64            `json:"total_count"`
}

func (q *Queries) GetTrashedMerchantDocuments(ctx context.Context, arg GetTrashedMerchantDocumentsParams) ([]*GetTrashedMerchantDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getTrashedMerchantDocuments, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTrashedMerchantDocumentsRow
	for rows.Next() {
		var i GetTrashedMerchantDocumentsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.MerchantID,
			&i.DocumentType,
			&i.DocumentUrl,
			&i.Status,
			&i.Note,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAllMerchantDocuments = `-- name: RestoreAllMerchantDocuments :exec
UPDATE merchant_documents
SET
    deleted_at = NULL
WHERE
    deleted_at IS NOT NULL
`

func (q *Queries) RestoreAllMerchantDocuments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreAllMerchantDocuments)
	return err
}

const restoreMerchantDocument = `-- name: RestoreMerchantDocument :one
UPDATE merchant_documents
SET
    deleted_at = NULL
WHERE
    document_id = $1
    AND deleted_at IS NOT NULL
RETURNING
    document_id,
    merchant_id,
    document_type,
    document_url,
    status,
    note,
    uploaded_at,
    created_at,
    updated_at,
    deleted_at
`

type RestoreMerchantDocumentRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) RestoreMerchantDocument(ctx context.Context, documentID int32) (*RestoreMerchantDocumentRow, error) {
	row := q.db.QueryRow(ctx, restoreMerchantDocument, documentID)
	var i RestoreMerchantDocumentRow
	err := row.Scan(
		&i.DocumentID,
		&i.MerchantID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Status,
		&i.Note,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashMerchantDocument = `-- name: TrashMerchantDocument :one
UPDATE merchant_documents
SET
    deleted_at = current_timestamp
WHERE
    document_id = $1
    AND deleted_at IS NULL
RETURNING
    document_id,
    merchant_id,
    document_type,
    document_url,
    status,
    note,
    uploaded_at,
    created_at,
    updated_at,
    deleted_at
`

type TrashMerchantDocumentRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) TrashMerchantDocument(ctx context.Context, documentID int32) (*TrashMerchantDocumentRow, error) {
	row := q.db.QueryRow(ctx, trashMerchantDocument, documentID)
	var i TrashMerchantDocumentRow
	err := row.Scan(
		&i.DocumentID,
		&i.MerchantID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Status,
		&i.Note,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateMerchantDocument = `-- name: UpdateMerchantDocument :one
UPDATE merchant_documents
SET
    document_type = $2,
    document_url = $3,
    status = $4,
    note = $5,
    updated_at = current_timestamp
WHERE
    document_id = $1
    AND deleted_at IS NULL
RETURNING
    document_id,
    merchant_id,
    document_type,
    document_url,
    status,
    note,
    uploaded_at,
    created_at,
    updated_at
`

type UpdateMerchantDocumentParams struct {
	DocumentID   int32   `json:"document_id"`
	DocumentType string  `json:"document_type"`
	DocumentUrl  string  `json:"document_url"`
	Status       string  `json:"status"`
	Note         *string `json:"note"`
}

type UpdateMerchantDocumentRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateMerchantDocument(ctx context.Context, arg UpdateMerchantDocumentParams) (*UpdateMerchantDocumentRow, error) {
	row := q.db.QueryRow(ctx, updateMerchantDocument,
		arg.DocumentID,
		arg.DocumentType,
		arg.DocumentUrl,
		arg.Status,
		arg.Note,
	)
	var i UpdateMerchantDocumentRow
	err := row.Scan(
		&i.DocumentID,
		&i.MerchantID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Status,
		&i.Note,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateMerchantDocumentStatus = `-- name: UpdateMerchantDocumentStatus :one
WITH valid_merchant AS (
    SELECT m.merchant_id
    FROM merchants m
    JOIN users u ON u.user_id = m.user_id AND u.deleted_at IS NULL
    WHERE m.merchant_id = (
        SELECT md.merchant_id FROM merchant_documents md
        WHERE md.document_id = $1 AND md.deleted_at IS NULL
    ) AND m.deleted_at IS NULL
), updated_document AS (
    UPDATE merchant_documents
    SET status = $2, note = $3, event_version = event_version + 1, updated_at = current_timestamp
    WHERE merchant_documents.document_id = $1
      AND merchant_documents.deleted_at IS NULL
      AND merchant_documents.merchant_id IN (SELECT valid_merchant.merchant_id FROM valid_merchant)
    RETURNING document_id, merchant_id, document_type, document_url, status, note, uploaded_at, created_at, updated_at, event_version
), queued_event AS (
    INSERT INTO outbox_events (event_key, topic, message_key, payload)
    SELECT
        'merchant-document-status:' || d.document_id::text || ':' || d.event_version::text,
        'email-service-topic-merchant-document-update-status',
        d.document_id::text,
        jsonb_build_object(
            'event_id', gen_random_uuid()::text,
            'schema_version', 1,
            'event_type', 'merchant_document.status_updated',
            'occurred_at', now(),
            'email', u.email,
            'subject', 'Merchant Document Status: ' || initcap(d.status),
            'body', 'Your merchant document status has been updated to ' || d.status || '.' || CASE WHEN d.note IS NULL OR d.note = '' THEN '' ELSE ' Reviewer note: ' || d.note END,
            'event_version', d.event_version
        )
    FROM updated_document d
    JOIN merchants m ON m.merchant_id = d.merchant_id AND m.deleted_at IS NULL
    JOIN users u ON u.user_id = m.user_id AND u.deleted_at IS NULL
    ON CONFLICT (event_key) DO NOTHING
    RETURNING event_key
)
SELECT d.document_id, d.merchant_id, d.document_type, d.document_url, d.status, d.note, d.uploaded_at, d.created_at, d.updated_at
FROM updated_document d
`

type UpdateMerchantDocumentStatusParams struct {
	DocumentID int32   `json:"document_id"`
	Status     string  `json:"status"`
	Note       *string `json:"note"`
}

type UpdateMerchantDocumentStatusRow struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateMerchantDocumentStatus(ctx context.Context, arg UpdateMerchantDocumentStatusParams) (*UpdateMerchantDocumentStatusRow, error) {
	row := q.db.QueryRow(ctx, updateMerchantDocumentStatus, arg.DocumentID, arg.Status, arg.Note)
	var i UpdateMerchantDocumentStatusRow
	err := row.Scan(
		&i.DocumentID,
		&i.MerchantID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Status,
		&i.Note,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
