// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingCycle struct {
	BillingID  int32            `json:"billing_id"`
	CardNumber string           `json:"card_number"`
	CycleStart time.Time        `json:"cycle_start"`
	CycleEnd   time.Time        `json:"cycle_end"`
	AmountDue  int32            `json:"amount_due"`
	DueDate    time.Time        `json:"due_date"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Card struct {
	CardID             int32            `json:"card_id"`
	UserID             int32            `json:"user_id"`
	CardNumber         string           `json:"card_number"`
	CardType           string           `json:"card_type"`
	ExpireDate         pgtype.Date      `json:"expire_date"`
	Cvv                string           `json:"cvv"`
	CardProvider       string           `json:"card_provider"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
	Status             string           `json:"status"`
	CreditLimit        int32            `json:"credit_limit"`
	OutstandingBalance int32            `json:"outstanding_balance"`
	RewardPoints       int32            `json:"reward_points"`
	EventVersion       int64            `json:"event_version"`
}

type CardAuthTransaction struct {
	AuthID         int32            `json:"auth_id"`
	TxnID          string           `json:"txn_id"`
	CardNumber     string           `json:"card_number"`
	MerchantID     int32            `json:"merchant_id"`
	Amount         int64            `json:"amount"`
	Currency       string           `json:"currency"`
	Mcc            string           `json:"mcc"`
	PosEntryMode   string           `json:"pos_entry_mode"`
	Status         string           `json:"status"`
	IdempotencyKey string           `json:"idempotency_key"`
	RiskScore      int32            `json:"risk_score"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type CardEventLog struct {
	EventID     int64     `json:"event_id"`
	Topic       string    `json:"topic"`
	EventType   string    `json:"event_type"`
	CardNumber  *string   `json:"card_number"`
	ReferenceID *string   `json:"reference_id"`
	Payload     []byte    `json:"payload"`
	ReceivedAt  time.Time `json:"received_at"`
}

type CardPayment struct {
	PaymentID      int32            `json:"payment_id"`
	PaymentUuid    string           `json:"payment_uuid"`
	CardNumber     string           `json:"card_number"`
	BillingID      *int32           `json:"billing_id"`
	Amount         int64            `json:"amount"`
	PaymentChannel string           `json:"payment_channel"`
	ReferenceID    string           `json:"reference_id"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type CardReward struct {
	RewardID     int32            `json:"reward_id"`
	CardNumber   string           `json:"card_number"`
	TxnID        string           `json:"txn_id"`
	Amount       int64            `json:"amount"`
	Mcc          string           `json:"mcc"`
	PointsEarned int32            `json:"points_earned"`
	ExpiresAt    time.Time        `json:"expires_at"`
	Redeemed     bool             `json:"redeemed"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type ConsumerInbox struct {
	ConsumerName       string             `json:"consumer_name"`
	EventKey           string             `json:"event_key"`
	Topic              string             `json:"topic"`
	PartitionID        int32              `json:"partition_id"`
	MessageOffset      int64              `json:"message_offset"`
	Status             string             `json:"status"`
	Attempts           int32              `json:"attempts"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	LastError          string             `json:"last_error"`
	ProcessedAt        pgtype.Timestamptz `json:"processed_at"`
	ReservationVersion int64              `json:"reservation_version"`
}

type Merchant struct {
	MerchantID   int32            `json:"merchant_id"`
	MerchantNo   pgtype.UUID      `json:"merchant_no"`
	Name         string           `json:"name"`
	ApiKey       string           `json:"api_key"`
	UserID       int32            `json:"user_id"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	EventVersion int64            `json:"event_version"`
}

type MerchantDocument struct {
	DocumentID   int32            `json:"document_id"`
	MerchantID   int32            `json:"merchant_id"`
	DocumentType string           `json:"document_type"`
	DocumentUrl  string           `json:"document_url"`
	Status       string           `json:"status"`
	Note         *string          `json:"note"`
	UploadedAt   pgtype.Timestamp `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	EventVersion int64            `json:"event_version"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	EventKey      string             `json:"event_key"`
	Topic         string             `json:"topic"`
	MessageKey    string             `json:"message_key"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	ClaimVersion  int64              `json:"claim_version"`
}

type RefreshToken struct {
	RefreshTokenID int32            `json:"refresh_token_id"`
	UserID         int32            `json:"user_id"`
	Token          string           `json:"token"`
	Expiration     time.Time        `json:"expiration"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type ResetToken struct {
	ID         int32     `json:"id"`
	UserID     int64     `json:"user_id"`
	Token      string    `json:"token"`
	ExpiryDate time.Time `json:"expiry_date"`
}

type Role struct {
	RoleID    int32            `json:"role_id"`
	RoleName  string           `json:"role_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Saldo struct {
	SaldoID        int32            `json:"saldo_id"`
	CardNumber     string           `json:"card_number"`
	TotalBalance   int32            `json:"total_balance"`
	WithdrawAmount *int32           `json:"withdraw_amount"`
	WithdrawTime   pgtype.Timestamp `json:"withdraw_time"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type Topup struct {
	TopupID        int32            `json:"topup_id"`
	TopupNo        pgtype.UUID      `json:"topup_no"`
	CardNumber     string           `json:"card_number"`
	TopupAmount    int32            `json:"topup_amount"`
	TopupMethod    string           `json:"topup_method"`
	TopupTime      time.Time        `json:"topup_time"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	IdempotencyKey string           `json:"idempotency_key"`
}

type Transaction struct {
	TransactionID   int32            `json:"transaction_id"`
	TransactionNo   pgtype.UUID      `json:"transaction_no"`
	CardNumber      string           `json:"card_number"`
	Amount          int32            `json:"amount"`
	PaymentMethod   string           `json:"payment_method"`
	MerchantID      int32            `json:"merchant_id"`
	TransactionTime time.Time        `json:"transaction_time"`
	Status          string           `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
	FraudScore      int32            `json:"fraud_score"`
	IdempotencyKey  string           `json:"idempotency_key"`
}

type Transfer struct {
	TransferID     int32            `json:"transfer_id"`
	TransferNo     pgtype.UUID      `json:"transfer_no"`
	TransferFrom   string           `json:"transfer_from"`
	TransferTo     string           `json:"transfer_to"`
	TransferAmount int32            `json:"transfer_amount"`
	TransferTime   time.Time        `json:"transfer_time"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	IdempotencyKey string           `json:"idempotency_key"`
}

type User struct {
	UserID           int32            `json:"user_id"`
	Firstname        string           `json:"firstname"`
	Lastname         string           `json:"lastname"`
	Email            string           `json:"email"`
	Password         string           `json:"password"`
	VerificationCode string           `json:"verification_code"`
	IsVerified       *bool            `json:"is_verified"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

type UserRole struct {
	UserRoleID int32            `json:"user_role_id"`
	UserID     int32            `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Withdraw struct {
	WithdrawID     int32            `json:"withdraw_id"`
	WithdrawNo     pgtype.UUID      `json:"withdraw_no"`
	CardNumber     string           `json:"card_number"`
	WithdrawAmount int32            `json:"withdraw_amount"`
	WithdrawTime   time.Time        `json:"withdraw_time"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	IdempotencyKey string           `json:"idempotency_key"`
}
