// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
    SELECT id
    FROM outbox_events
    WHERE ((status = 'pending' AND next_attempt_at <= current_timestamp)
       OR (status = 'publishing' AND updated_at < current_timestamp - interval '1 minute'))
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE outbox_events e
SET status = 'publishing', attempts = e.attempts + 1,
    claim_version = e.claim_version + 1,
    updated_at = current_timestamp
FROM candidates c
WHERE e.id = c.id
RETURNING e.id, e.topic, e.message_key, e.payload, e.attempts, e.claim_version
`

type ClaimOutboxEventsRow struct {
	ID           int64  `json:"id"`
	Topic        string `json:"topic"`
	MessageKey   string `json:"message_key"`
	Payload      []byte `json:"payload"`
	Attempts     int32  `json:"attempts"`
	ClaimVersion int64  `json:"claim_version"`
}

// ClaimOutboxEvents: Claims eligible outbox events for publishing.
func (q *Queries) ClaimOutboxEvents(ctx context.Context, limit int32) ([]*ClaimOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ClaimOutboxEventsRow
	for rows.Next() {
		var i ClaimOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.MessageKey,
			&i.Payload,
			&i.Attempts,
			&i.ClaimVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimOutboxEventsByTopics = `-- name: ClaimOutboxEventsByTopics :many
WITH candidates AS (
    SELECT id
    FROM outbox_events
    WHERE ((status = 'pending' AND next_attempt_at <= current_timestamp)
       OR (status = 'publishing' AND updated_at < current_timestamp - interval '1 minute'))
      AND topic = ANY($2::text[])
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE outbox_events e
SET status = 'publishing', attempts = e.attempts + 1,
    claim_version = e.claim_version + 1,
    updated_at = current_timestamp
FROM candidates c
WHERE e.id = c.id
RETURNING e.id, e.topic, e.message_key, e.payload, e.attempts, e.claim_version
`

type ClaimOutboxEventsByTopicsParams struct {
	Limit   int32    `json:"limit"`
	Column2 []string `json:"column_2"`
}

type ClaimOutboxEventsByTopicsRow struct {
	ID           int64  `json:"id"`
	Topic        string `json:"topic"`
	MessageKey   string `json:"message_key"`
	Payload      []byte `json:"payload"`
	Attempts     int32  `json:"attempts"`
	ClaimVersion int64  `json:"claim_version"`
}

// ClaimOutboxEventsByTopics: Claims eligible outbox events for selected topics.
func (q *Queries) ClaimOutboxEventsByTopics(ctx context.Context, arg ClaimOutboxEventsByTopicsParams) ([]*ClaimOutboxEventsByTopicsRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxEventsByTopics, arg.Limit, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ClaimOutboxEventsByTopicsRow
	for rows.Next() {
		var i ClaimOutboxEventsByTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.MessageKey,
			&i.Payload,
			&i.Attempts,
			&i.ClaimVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :exec
INSERT INTO outbox_events (event_key, topic, message_key, payload)
VALUES ($1, $2, $3, $4::jsonb)
ON CONFLICT (event_key) DO NOTHING
`

type EnqueueOutboxEventParams struct {
	EventKey   string `json:"event_key"`
	Topic      string `json:"topic"`
	MessageKey string `json:"message_key"`
	Column4    []byte `json:"column_4"`
}

// EnqueueOutboxEvent: Persists an outbox event in the caller's transaction.
func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) error {
	_, err := q.db.Exec(ctx, enqueueOutboxEvent,
		arg.EventKey,
		arg.Topic,
		arg.MessageKey,
		arg.Column4,
	)
	return err
}

const markConsumerInboxProcessed = `-- name: MarkConsumerInboxProcessed :exec
UPDATE consumer_inbox
SET status = 'processed', processed_at = current_timestamp,
    lease_until = current_timestamp, last_error = ''
WHERE consumer_name = $1 AND event_key = $2
  AND status = 'processing' AND reservation_version = $3
`

type MarkConsumerInboxProcessedParams struct {
	ConsumerName       string `json:"consumer_name"`
	EventKey           string `json:"event_key"`
	ReservationVersion int64  `json:"reservation_version"`
}

// MarkConsumerInboxProcessed: Completes only the active reservation.
func (q *Queries) MarkConsumerInboxProcessed(ctx context.Context, arg MarkConsumerInboxProcessedParams) error {
	_, err := q.db.Exec(ctx, markConsumerInboxProcessed, arg.ConsumerName, arg.EventKey, arg.ReservationVersion)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox_events
SET status = $2,
    next_attempt_at = current_timestamp + $3::interval,
    last_error = $4,
    updated_at = current_timestamp
WHERE id = $1 AND status = 'publishing' AND claim_version = $5
`

type MarkOutboxFailedParams struct {
	ID           int64           `json:"id"`
	Status       string          `json:"status"`
	Column3      pgtype.Interval `json:"column_3"`
	LastError    string          `json:"last_error"`
	ClaimVersion int64           `json:"claim_version"`
}

// MarkOutboxFailed: Records a failed publish only for the active claim.
func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed,
		arg.ID,
		arg.Status,
		arg.Column3,
		arg.LastError,
		arg.ClaimVersion,
	)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox_events
SET status = 'published', published_at = current_timestamp,
    updated_at = current_timestamp, last_error = ''
WHERE id = $1 AND status = 'publishing' AND claim_version = $2
`

type MarkOutboxPublishedParams struct {
	ID           int64 `json:"id"`
	ClaimVersion int64 `json:"claim_version"`
}

// MarkOutboxPublished: Marks an event published only for the active claim.
func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, arg.ID, arg.ClaimVersion)
	return err
}

const releaseConsumerInbox = `-- name: ReleaseConsumerInbox :exec
UPDATE consumer_inbox
SET status = 'pending', lease_until = current_timestamp,
    last_error = $3
WHERE consumer_name = $1 AND event_key = $2
  AND status = 'processing' AND reservation_version = $4
`

type ReleaseConsumerInboxParams struct {
	ConsumerName       string `json:"consumer_name"`
	EventKey           string `json:"event_key"`
	LastError          string `json:"last_error"`
	ReservationVersion int64  `json:"reservation_version"`
}

// ReleaseConsumerInbox: Releases only the active reservation.
func (q *Queries) ReleaseConsumerInbox(ctx context.Context, arg ReleaseConsumerInboxParams) error {
	_, err := q.db.Exec(ctx, releaseConsumerInbox,
		arg.ConsumerName,
		arg.EventKey,
		arg.LastError,
		arg.ReservationVersion,
	)
	return err
}

const reserveConsumerInbox = `-- name: ReserveConsumerInbox :one
WITH reserved AS (
    INSERT INTO consumer_inbox (
        consumer_name, event_key, topic, partition_id, message_offset,
        status, attempts, reservation_version, lease_until, last_error, processed_at
    )
    VALUES ($1, $2, $3, $4, $5, 'processing', 1, 1,
            current_timestamp + interval '1 minute', '', NULL)
    ON CONFLICT (consumer_name, event_key) DO UPDATE
    SET status = 'processing',
        attempts = consumer_inbox.attempts + 1,
        reservation_version = consumer_inbox.reservation_version + 1,
        lease_until = current_timestamp + interval '1 minute',
        last_error = '',
        topic = EXCLUDED.topic,
        partition_id = EXCLUDED.partition_id,
        message_offset = EXCLUDED.message_offset
    WHERE consumer_inbox.status <> 'processed'
      AND consumer_inbox.lease_until <= current_timestamp
    RETURNING reservation_version
)
SELECT
    EXISTS (SELECT 1 FROM reserved) AS reserved,
    EXISTS (
        SELECT 1
        FROM consumer_inbox ci
        WHERE ci.consumer_name = $1
          AND ci.event_key = $2
          AND ci.status = 'processed'
    ) AS processed,
    COALESCE(
        (SELECT reservation_version FROM reserved),
        (SELECT ci.reservation_version FROM consumer_inbox ci WHERE ci.consumer_name = $1 AND ci.event_key = $2)
    )::BIGINT AS reservation_version
`

type ReserveConsumerInboxParams struct {
	ConsumerName  string `json:"consumer_name"`
	EventKey      string `json:"event_key"`
	Topic         string `json:"topic"`
	PartitionID   int32  `json:"partition_id"`
	MessageOffset int64  `json:"message_offset"`
}

type ReserveConsumerInboxRow struct {
	Reserved           bool  `json:"reserved"`
	Processed          bool  `json:"processed"`
	ReservationVersion int64 `json:"reservation_version"`
}

// ReserveConsumerInbox: Claims an event and returns whether this call owns the reservation.
func (q *Queries) ReserveConsumerInbox(ctx context.Context, arg ReserveConsumerInboxParams) (*ReserveConsumerInboxRow, error) {
	row := q.db.QueryRow(ctx, reserveConsumerInbox,
		arg.ConsumerName,
		arg.EventKey,
		arg.Topic,
		arg.PartitionID,
		arg.MessageOffset,
	)
	var i ReserveConsumerInboxRow
	err := row.Scan(&i.Reserved, &i.Processed, &i.ReservationVersion)
	return &i, err
}
